### ISSUE TITLE
Update to angular2 Rc5 and rc6

### ISSUE THREAD

**Issue by Ks89** [SirDarquan/h5webstorage#9]
With rc5, if you execute this "npm install h5webstorage --save" you'll get:

├── UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.5
├── UNMET PEER DEPENDENCY @angular/forms@0.3.0
└── h5webstorage@0.5.2

npm WARN ng2-bootstrap@1.0.24 requires a peer of @angular/common@2.0.0-rc.4 but none was installed.
npm WARN ng2-bootstrap@1.0.24 requires a peer of @angular/compiler@2.0.0-rc.4 but none was installed.
npm WARN ng2-bootstrap@1.0.24 requires a peer of @angular/core@2.0.0-rc.4 but none was installed.
npm WARN ng2-bootstrap@1.0.24 requires a peer of @angular/forms@0.2.0 but none was installed.

**Comment by Ks89** [comment]
It's working also with RC5. There are only some warnings during the installation process.

**Comment by SirDarquan** [comment]
I'm so sorry, I missed this notification in my email. So yeah, I originally compiled this with rc4 and haven't had a chance to see how it plays with rc5. I'll play with that a little bit and see if I can get a new release sometime this week.

Thanks for letting me know.

**Comment by Ks89** [comment]
Thank u very much.
Ks89.

**Comment by Ks89** [comment]
A little update. With RC6 I receive this error by Systemjs

zone.js:484 Unhandled Promise rejection: (SystemJS) core_1.provide is not a function
    TypeError: core_1.provide is not a function
        at Object.eval 
(http://localhost:3000/node_modules/h5webstorage/index.js:17:12)
        at eval (http://localhost:3000/node_modules/h5webstorage/index.js:57:4)
        at eval (http://localhost:3000/node_modules/h5webstorage/index.js:58:3)
    Evaluating http://localhost:3000/node_modules/h5webstorage/index.js
    Error loading http://localhost:3000/app/main.ts ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) core_1.provide is not a function(…) nullconsoleError @ zone.js:484_loop_1 @ zone.js:511drainMicroTaskQueue @ zone.js:515ZoneTask.invoke @ zone.js:437
zone.js:486 Error: Uncaught (in promise): Error: (SystemJS) core_1.provide is not a function(…)consoleError @ zone.js:486_loop_1 @ zone.js:511drainMicroTaskQueue @ zone.js:515ZoneTask.invoke @ zone.js:437

**Comment by SirDarquan** [comment]
Thanks again. Sorry this is taking so long to get done. I feel like I have to learn everything all over again. lol

**Comment by SirDarquan** [comment]
Here's an update on my end: The code for h5webstorage itself was not affected by the recent release candidates 5 & 6. The problem was actually the testing methodology I used which was based on RC3 testing api. It was only deprecated in RC4 but actually removed in RC5, hence the initial reported issue. Looking over the RC6 change log reveals larger dependency changes, most notably using TypeScript 2 beta. This change caused compile errors so I'm locking the dependencies to RC5 for now. This will allow those who want to pull the source will now be able to build without issue up to RC5 but those whose just used the npm package can also develop against RC6.

Does this satisfy what you need?

**Comment by SirDarquan** [comment]
You know, when I first saw this issue, I assumed it was because of the changes in angular2 that I thought I'd been careful to plan for. But looking at it again, the issue that you put in the coments were for ng2-bootstrap, not for h5webstorage. But thanks anyway for making me do the updates for RC5 testing :) 

Now as far as the issues with RC6, you'll have to give me more to go on to allow me to actually help fix things. Can you make a fiddle or pen or whatever to demonstrate how the issue occurs.

**Comment by Ks89** [comment]
Hi,
I tried with a clean angular rc6 project, but I'm receiving this:

zone.js:484 Unhandled Promise rejection: (SystemJS) core_1.provide is not a function
    TypeError: core_1.provide is not a function
        at Object.eval 

Probably, this is not related to your library. I suppose the I should check how to change my systemjs config file for RC6.

I'll update this issue during the next week 👍

**Comment by stijn26** [comment]
I have the same error with RC6:
TypeError: core_1.provide is not a function
at Object.eval 

Not using SystemJS but Webpack (Angular-CLI)

**Comment by Calderis** [comment]
Same for me.

I'm based on Angular Heroes tutorial and so I'm using SystemJS.

**Comment by SirKnightDragoon** [comment]
Same bug here.. so I just remove h5webstorage and using the default html5 localStorage.

You just need to add this on top of your component:

declare var localStorage:any;

And continue to use your code:

localStorage.getItem("save")

**Comment by Ks89** [comment]
@SirKnightDragoon Yes, at the moment I'm using the same technique.

**Comment by SirDarquan** [comment]
Ok I feel like I'm missing something here. I have tests that say the way you all are accessing the api should work. Would it be possible for someone to make a github branch that contains the complete code that's failing. I need to see the setup and everything to make a better determination of what my code is doing wrong, if anything.  I want to help but when I setup it up it works. That's probably because I understand the capabilities. Maybe it's being used in a way I didn't anticipate (It's happened before)

**Comment by nemo97** [comment]
export const gatesRoutingProviders: any[] = [  
    WEB_STORAGE_PROVIDERS,
    ConfigureStorage({ prefix: "mygates-" })
];

Register above providers to ModuleProviders, it was working with rc5 but not working with rc6. using webpack

![capture](https://cloud.githubusercontent.com/assets/547721/18413556/05421372-7760-11e6-8ca8-ac5fa77e8fd3.PNG)

**Comment by pkapare** [comment]
Any updates on this issue?

**Comment by SirDarquan** [comment]
I've decided to rebuild the library from scratch so that it complies with the final Angular2 build. It will havethe same APIs exposed but I'm not going to ensure compatibility with any of the release candidates. Hopefully I'll have it available soon.

**Comment by SirDarquan** [comment]
Updated code has been released. Let me know if there are any issues.
